name: Release

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    permissions:
      contents: write
      pull-requests: write
    uses: studiage/gha-workflow/.github/workflows/reusable-bump-version.yml@v0.0.1
    with:
      release-branch: main
      node-version: "24"
